# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Phani Raj
email: phanirajuyn@gmail.com
description: Staff Software Engineer at GitHub
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://phanatic.github.io" # the base hostname & protocol for your site
twitter_username: phanirajuyn
github_username:  phanatic

# Build settings
markdown: kramdown

gems:
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji
paginate: 7
